In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e12/sample_submission.csv
/kaggle/input/playground-series-s4e12/train.csv
/kaggle/input/playground-series-s4e12/test.csv

In [31]:
import pandas as pd 
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OrdinalEncoder

In [10]:
df_train = pd.read_csv('/kaggle/input/playground-series-s4e12/train.csv')
df_train.head()

(1200000, 21)

In [29]:
df_train.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Vehicle Age,Credit Score,Insurance Duration,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,Premium,17.0,372.0,5.0,No,Weekly,House,2869.0
1,39.0,Female,31678.0,Divorced,3.0,Master's,mode,15.569731,Rural,Comprehensive,12.0,694.0,2.0,Yes,Monthly,House,1483.0
2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,Premium,14.0,median,3.0,Yes,Weekly,House,567.0
3,21.0,Male,141855.0,Married,2.0,Bachelor's,mode,10.938144,Rural,Basic,0.0,367.0,1.0,Yes,Daily,Apartment,765.0
4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,Premium,8.0,598.0,4.0,Yes,Weekly,House,2022.0

In [33]:
df_train['Marital Status'].unique()

array(['Married', 'Divorced', 'Single', 'mode'], dtype=object)

In [ ]:
categorical = ['Gender']

In [21]:
df_train.isnull().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Vehicle Age             0
Credit Score            0
Insurance Duration      0
Smoking Status          0
Exercise Frequency      0
Property Type           0
Premium Amount          0
dtype: int64

In [13]:
#dropping columns with different datatypes
to_drop = ['id','Customer Feedback','Previous Claims','Policy Start Date']
df_train.drop(columns = to_drop,inplace = True)

In [20]:
to_fillna_median = ['Credit Score',"Health Score",'Number of Dependents','Annual Income',"Age","Insurance Duration",'Vehicle Age']
to_fillna_mode = ['Occupation','Marital Status']

df_train[to_fillna_median] = df_train[to_fillna_median].fillna('median')
df_train[to_fillna_mode] = df_train[to_fillna_mode].fillna('mode')

In [28]:
X = df_train.drop(columns = ['Premium Amount'])
y = df_train['Premium Amount']

In [27]:
gb_model = GradientBoostingRegressor()
param_grid = {
    'n_estimators':[80,90,100,110],
    "max_depth":[10,15,20]
}
grid = GridSearchCV(gb_model,param_grid = param_grid,cv = 4,n_jobs = -1)